#!/bin/bash
programs=(
    # basic programs
    "git"
    "neofetch"

    # xorg-programs
    "xorg-server"
    "xorg-xinit"
    "xorg-xset"
    "xorg-setxkbmap"
    "xorg-xrandr"
    "xcompmgr"
    "xwallpaper"
    "xclip"
    "xsel"
    "light"

    # user programs
    "flameshot"
    "brave-bin"
    "firefox"
    "neovim"
    "npm"
    "clang"
    "pavucontrol"
    "sxiv"
    "mpv"
    "delta-git"
    "zsh"
    "zsh-syntax-highlighting-git"
    "newsboat"
    "yt-dlp"
)

for package in "${programs[@]}"
do
    yay -S $package --noconfirm
    pid=$(pidof -x yay)
    while [ -n "$pid" ]
    do
        sleep 2
        pid=$(pidof -x yay)
    done
done
