# Shell variables
# Generated by 'wal'
wallpaper="/home/sahil/dark.jpg"

# Special
background='#040506'
foreground='#c0c0c0'
cursor='#c0c0c0'

# Colors
color0='#040506'
color1='#3E5861'
color2='#455258'
color3='#475C63'
color4='#526971'
color5='#696A6D'
color6='#637B83'
color7='#c0c0c0'
color8='#424344'
color9='#3E5861'
color10='#455258'
color11='#475C63'
color12='#526971'
color13='#696A6D'
color14='#637B83'
color15='#c0c0c0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
