--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sahil/.config/repos/Pictures/mainwallpapers/newsecond.jpg"

-- Special
background="#020307"
foreground="#bfc0c1"
cursor="#bfc0c1"

-- Colors
color0="#020307"
color1="#4A3C42"
color2="#334553"
color3="#3D5462"
color4="#4D4B54"
color5="#605959"
color6="#9E6B4B"
color7="#bfc0c1"
color8="#414245"
color9="#4A3C42"
color10="#334553"
color11="#3D5462"
color12="#4D4B54"
color13="#605959"
color14="#9E6B4B"
color15="#bfc0c1"
