--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sahil/dark.jpg"

-- Special
background="#040506"
foreground="#c0c0c0"
cursor="#c0c0c0"

-- Colors
color0="#040506"
color1="#3E5861"
color2="#455258"
color3="#475C63"
color4="#526971"
color5="#696A6D"
color6="#637B83"
color7="#c0c0c0"
color8="#424344"
color9="#3E5861"
color10="#455258"
color11="#475C63"
color12="#526971"
color13="#696A6D"
color14="#637B83"
color15="#c0c0c0"
