# Shell variables
# Generated by 'wal'
wallpaper="/home/sahil/.config/repos/Pictures/mainwallpapers/newsecond.jpg"

# Special
background='#020307'
foreground='#bfc0c1'
cursor='#bfc0c1'

# Colors
color0='#020307'
color1='#4A3C42'
color2='#334553'
color3='#3D5462'
color4='#4D4B54'
color5='#605959'
color6='#9E6B4B'
color7='#bfc0c1'
color8='#414245'
color9='#4A3C42'
color10='#334553'
color11='#3D5462'
color12='#4D4B54'
color13='#605959'
color14='#9E6B4B'
color15='#bfc0c1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
